spring:
  mvc:
    log-request-details: true
logging:
  level:
    web: debug
server:
  port: 8080
  compression:
    enabled: true
  http2:
    enabled: true
springy:
  config-properties:
    stringparam: abc
    intparam: 123
    booleanparam: true
    conversion-param: hello
    duration-param: 20s
    datasize-param: 20MB
    null-param: ~
    wrong-validation-param: 123
    objectparam:
      stringparam: abc
      intparam: 123
      booleanparam: true
