spring:
  jpa:
    properties:
      hibernate.format_sql: true
    generate-ddl: true
    show-sql: true
  mvc:
    log-request-details: true
  h2:
    console:
      enabled: true
logging:
  level:
    web: debug
    org.hibernate:
      SQL: DEBUG
      type:
        descriptor:
          sql:
            BasicBinder: TRACE
server:
  port: 8080
  compression:
    enabled: true
  http2:
    enabled: true
  shutdown: graceful
springy:
  config-properties:
    stringparam: abc
    intparam: 123
    booleanparam: true
    conversion-param: hello
    duration-param: 20s
    datasize-param: 20MB
    null-param: ~
    wrong-validation-param: 123
    objectparam:
      stringparam: abc
      intparam: 123
      booleanparam: true
