name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Java JDK
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 11

      - name: execute gradle build
        run: ./gradlew clean build

      - name: build docker image
        run: docker build . -t springy:latest

